on:
 pull_request:
 push:
   branches: [master, develop]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
     - uses: actions/checkout@v2
       with:
         submodules: true
     - uses: cachix/install-nix-action@v14.1
     - uses: cachix/cachix-action@v10
       with:
         name: wire-server
         signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         role-to-assume: arn:aws:iam::093205192929:role/gh-actions-wire-server
         aws-region: eu-west-1
     - name: test assumed role works
       run: |
         aws s3 ls s3://origin-docs.wire.com/
